# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dc4a1b21580a65fedf1644807552444663a2b7b77489fa69fa798c5c2087661b354b9c59ba3a479c2d3774a0bf028fd5a152114583fd6bbc95c6ca18b2a7cba

test:
  secret_key_base: 275ca248c685dc6651818e091633bd6ca1abc7f8b5bf0edb70394a9efefe550bf053f0c61fab97901caee6c1c5468fdb1d2933f1631b23732e884bc05370c66c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
